# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Magicbell's Blog
name: "Ling Mao"
email: sophieml1989@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Never give a limitation of what I can do.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://magicbell.beanstu.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: imagicbell
repository: "imagicbell.github.io"

# Build settings
markdown: kramdown
#theme: minima
remote_theme: "imagicbell/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

paginate: 8 # amount of posts to show
paginate_path: /page:num/

minimal_mistakes_skin : "default" # "air", "contrast", "dark", "dirt", "mint", "sunrise"
locale: "en" #"zh-CN", "en-GB", "en-US"
#teaser: /assets/images/NZ1.png
# breadcrumbs: true

include: ["_pages"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
# category_archive:
#   type: jekyll-archives
#   path: /categories/
# tag_archive:
#   type: jekyll-archives
#   path: /tags/
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

comments:
  provider: "disqus"
  disqus:
    shortname: "http-magicbell-beanstu-io"
    
google-site-verification: "Vl-emHXfE2xQ79AiY36Te1farfhFDS5lx-Rn5kESYmM"
bing_site_verification: "10190c188919dfbd8b2f50854c924a83"
